name: Release Pipeline

on:
  # PR validation - run dry-run for all feature PRs
  pull_request:
    branches: [main]
  
  # Automatic triggers
  push:
    branches: 
      - main          # Production release
      - 'rc/**'       # Release candidates
  
  # Manual trigger only for pre-release
  workflow_dispatch:
    inputs:
      notes:
        description: "Notes for pre-release"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

concurrency:
  # Prevent concurrent releases but allow concurrent PRs
  group: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'release-main' || github.run_id }}
  cancel-in-progress: false

jobs:
  # Job 1: Validate PRs with version prediction (ONLY for PRs)
  validate-pr:
    name: "Version Prediction"
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Predict and validate version
        id: dry-run
        uses: ./.github/actions/release-dry-run
        with:
          target-branch: main
          release-type: simple
          package-name: workflows
          path: "."

  # Job 2: Create release candidates (ONLY for rc/* branches OR manual trigger)
  release-candidate:
    name: "Create Release Candidate"
    if: >
      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/rc/')) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release candidate
        id: rc
        uses: ./.github/actions/pre-release-rc
        with:
          target-branch: main
          release-type: simple
          package-name: workflows
          path: "."
          notes: ${{ github.event.inputs.notes || 'Release candidate for testing' }}
          create-release: "false"

  # Job 3: Create production releases (ONLY for main branch pushes)
  production-release:
    name: "Production Release"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create production release
        id: release
        uses: ./.github/actions/release
        with:
          release-type: simple